// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5jKFtls8rlIu0fn8y-0wdY6kcktRSio',
    appId: '1:477640593911:web:ff20f11c4a9d9116c45ef2',
    messagingSenderId: '477640593911',
    projectId: 'flutter-demo-duczau',
    authDomain: 'flutter-demo-duczau.firebaseapp.com',
    databaseURL: 'https://flutter-demo-duczau-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-demo-duczau.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkk4IDCvQ9a2iKtpuLkehc2XSvJeiFEkM',
    appId: '1:477640593911:android:4c99b3e810143e76c45ef2',
    messagingSenderId: '477640593911',
    projectId: 'flutter-demo-duczau',
    databaseURL: 'https://flutter-demo-duczau-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-demo-duczau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWiu4S2M5O4BNLdKQ0QE7cP6Yl8ouhFPc',
    appId: '1:477640593911:ios:8586f0fa4c8396adc45ef2',
    messagingSenderId: '477640593911',
    projectId: 'flutter-demo-duczau',
    databaseURL: 'https://flutter-demo-duczau-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-demo-duczau.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWiu4S2M5O4BNLdKQ0QE7cP6Yl8ouhFPc',
    appId: '1:477640593911:ios:8586f0fa4c8396adc45ef2',
    messagingSenderId: '477640593911',
    projectId: 'flutter-demo-duczau',
    databaseURL: 'https://flutter-demo-duczau-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-demo-duczau.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW5jKFtls8rlIu0fn8y-0wdY6kcktRSio',
    appId: '1:477640593911:web:f8ac219dbcc78991c45ef2',
    messagingSenderId: '477640593911',
    projectId: 'flutter-demo-duczau',
    authDomain: 'flutter-demo-duczau.firebaseapp.com',
    databaseURL: 'https://flutter-demo-duczau-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-demo-duczau.firebasestorage.app',
  );
}
